[tools]
python = "3.13"
shellcheck = "latest"
uv = "latest"
deno = "latest"

[env._.python]
venv = { path = ".venv", create = true }

[vars]
pip_compile = "uv pip compile -q --upgrade --no-header --annotation-style=line"

[tasks.bump-reqs]
run = [
  "zsh -c '. ./.zpy/zpy.plugin.zsh; pypc -y'",
  "{{vars.pip_compile}} reqs/requirements.in reqs/sentry-requirements.in -o mouse_ran_down/requirements.txt",
  "{{vars.pip_compile}} reqs/dev-requirements.in                         -o dev-requirements.txt"
]

[tasks.install]
run = [
  "uv -q pip sync dev-requirements.txt",
  "uv -q pip install -e '.[dev]' -c dev-requirements.txt",
]

[tasks.fmt]
depends = ["install"]
run = [
  "shellcheck mk/*.sh start/*.sh",
  "ssort",
  "ruff format",
  "ruff check --fix",
  "pyright --warnings"
]
