[tools]
python = "3.13"
shellcheck = "latest"

[env._.python]
venv = { path = ".venv", create = true }

[tasks.ensure-uv]
run = "command -v uv || python -m pip install uv"
hide = true

[tasks.bump-reqs]
depends = ["ensure-uv"]
run = [
  "uv pip compile --python python -o mouse_ran_down/requirements.txt --no-header --annotation-style=line -U requirements.in",
  "uv pip compile --python python -o dev-requirements.txt --no-header --annotation-style=line -U dev-requirements.in"
]

[tasks.install]
depends = ["ensure-uv"]
run = "uv pip install -p python -r dev-requirements.txt"

[tasks.fmt]
depends = ["install"]
run = [
  "shellcheck mk/*.sh start/*.sh",
  "ssort",
  "ruff format",
  "ruff check --fix",
  "pyright --warnings"
]
