name: Build and push to ghcr.io
on:
  push:
  # schedule:
  #   - cron: '6 4 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Set container registry image name
        run: echo "CTNR_IMG=$(echo "ghcr.io/$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')" >>$GITHUB_ENV

      - uses: actions/checkout@v4

      - name: login to container registry
        run: podman login -u "$GITHUB_REPOSITORY_OWNER" -p "$TOKEN" ghcr.io
        env:
          TOKEN: ${{ secrets.GHCR_PAT }}

      - name: build container
        run: ./mk/ctnr.sh --connect-repo "$GITHUB_REPOSITORY" "$CTNR_IMG"

      - name: push container images
        run: |
          echo "All images:"
          podman images
          echo "Matching images:"
          podman images -n -f reference="$CTNR_IMG" --format={{.Repository}}:{{.Tag}}
          for img in $(podman images -n -f reference="$CTNR_IMG" --format={{.Repository}}:{{.Tag}}); do
            podman push "$img"
          done
