name: Build and push to quay.io
on:
  push:
  schedule:
    - cron: '6 4 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: login to container registry
        run: podman login -u "$GITHUB_REPOSITORY_OWNER" -p "$TOKEN" ghcr.io
        env:
          TOKEN: ${{ secrets.PAT }}

      - name: build container
        run: ./mk/ctnr.sh "ghcr.io/$GITHUB_REPOSITORY"

      - name: push container images
        run: |
          echo "All images:"
          podman images
          echo "Matching images:"
          podman images -n -f reference="ghcr.io/$GITHUB_REPOSITORY" --format={{.Repository}}:{{.Tag}}
          for img in $(podman images -n -f reference="ghcr.io/$GITHUB_REPOSITORY" --format={{.Repository}}:{{.Tag}}); do
            podman push "$img"
          done
