name: Build and push to quay.io
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: login to container registry
        run: podman login -u "$QUAY_USER" -p "$QUAY_TOKEN" quay.io
        env:
          QUAY_USER: ${{ secrets.QUAY_USER }}
          QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}

      - name: build container
        run: ./mk/ctnr.sh

      - name: push container images
        run: |
          echo "All images:"
          podman images
          echo "Matching images:"
          podman images -n -f reference='andykluger/*' --format={{.Repository}}:{{.Tag}}
          for img in $(podman images -n -f reference='andykluger/*' --format={{.Repository}}:{{.Tag}}); do
            podman push "$img"
          done
