name: Format and Lint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - run: pipx install uv

      - run: shellcheck mk/*.sh start/*.sh

      - run: uv run --with ssort ssort            app/main.py
      - run: uv run --with ruff  ruff format      app/main.py
      - run: uv run --with ruff  ruff check --fix app/main.py

      - run: uv run --with pyright --with-requirements app/requirements.txt pyright --warnings app/main.py

      - name: push it
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git commit -am 'Format & lint [Automated]' && git push || true
