name: Update requirements
on:
  workflow_dispatch:
  schedule:
    - cron: '5 4 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - uses: jdx/mise-action@v2

      - run: mise tasks run bump-reqs

      - name: push it
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git commit -am 'Bump PyPI requirements [Automated]' && git push || true
